name: CI

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      
      - name: Check Formatting
        run: nix develop .#default -c cargo fmt --manifest-path ./crates/Cargo.toml --check

      - name: Clippy
        run: nix develop .#default -c cargo clippy --manifest-path ./crates/Cargo.toml  --lib -p legato

  build:
    needs: lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Nix Build
        run: nix build . --print-build-logs

      - name: Nix Test
        run: nix develop .#default -c cargo test --manifest-path ./crates/Cargo.toml --workspace